stages:
  - lint
  - build

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:8083": {"auth": "$DOCKER_AU_CONFIG"}}}'
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PACKAGE_PATH: /go/src/gade/srv-goldcard

lint:
  image:
    name: artifactory.pegadaian.co.id:8083/dian/golangci:v1.23.1
    entrypoint: [""]
  stage: lint
  script:
    - go mod download
    - golangci-lint run
  only:
    - merge_requests

build:
  stage: build
  image: artifactory.pegadaian.co.id:8083/docker:latest
  services:
    - name: artifactory.pegadaian.co.id:8083/docker:dind
      command: ["--insecure-registry=artifactory.pegadaian.co.id:8083"]
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:8083
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
