stages:
  - lint
  - build
  - deploy

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:8084": {"auth": "$DOCKER_AU_CONFIG"},"artifactory.pegadaian.co.id:5443": {"auth": "$DOCKER_AU_CONFIG"}}}'
  IMAGE_URL: artifactory.pegadaian.co.id:5443/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  PACKAGE_PATH: /go/src/gade/srv-goldcard
  OPENSHIFT_REGION: sby
  OPENSHIFT_OC_URL: https://api.ocp-$OPENSHIFT_REGION.pegadaian.co.id:6443

# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}
      && export GO111MODULE=on
      && export PATH="$PATH:/go/bin"
      && export GOPROXY="https://artifactory.pegadaian.co.id/repository/go-group-01/"
      && cp ssl_certificate.crt /usr/local/share/ca-certificates
      && chmod 644 /usr/local/share/ca-certificates/ssl_certificate.crt && update-ca-certificates

.store_commit_hash: &store_commit_hash
  before_script:
    - touch latest_commit_hash
    - echo $CI_COMMIT_SHA > latest_commit_hash
    - echo $CI_COMMIT_TIMESTAMP >> latest_commit_hash

lint:
  image:
    name: artifactory.pegadaian.co.id:8084/golangci/golangci-lint:v1.42.1
    entrypoint: [""]
  stage: lint
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - golangci-lint run
  only:
    - merge_requests

build:
  stage: build
  image: artifactory.pegadaian.co.id:8084/docker:latest
  services:
    - name: artifactory.pegadaian.co.id:8084/docker:dind
      command: ["--insecure-registry=artifactory.pegadaian.co.id:8084"]
  <<: *store_commit_hash
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:8084
    - docker build --pull -t $IMAGE_URL .
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:5443
    - docker push $IMAGE_URL
  only:
    - master

deploy_dev:
  image: artifactory.pegadaian.co.id:8084/tj/openshift-client:latest
  stage: deploy
  script:
    - while true; do result=0; oc login -u $OC_USER -p $OC_PASS --server=$OPENSHIFT_OC_URL --insecure-skip-tls-verify || result=$?; tj=$((tj+1)); if [ $result -eq 0 ]; then break; elif [ $tj -gt 5 ]; then exit 1; fi; echo "retry $tj";done;
    - oc rollout latest dc/srv-goldcard-master
  only:
    - master
