stages:
  - lint
  - build

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:8084": {"auth": "$DOCKER_AU_CONFIG"},"artifactory.pegadaian.co.id:5443": {"auth": "$DOCKER_AU_CONFIG"}}}'
  IMAGE_URL: artifactory.pegadaian.co.id:5443/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  PACKAGE_PATH: /go/src/gade/srv-goldcard

lint:
  image:
    name: artifactory.pegadaian.co.id:8084/dian/golangci:v1.23.1
    entrypoint: [""]
  stage: lint
  script:
    - cp ssl_certificate.crt /usr/local/share/ca-certificates
    - chmod 644 /usr/local/share/ca-certificates/ssl_certificate.crt && update-ca-certificates
    - export GOPROXY="https://artifactory.pegadaian.co.id/repository/go-group-01/"
    - go mod download
    - golangci-lint run
  only:
    - merge_requests

build:
  stage: build
  image: artifactory.pegadaian.co.id:8084/docker:latest
  services:
    - name: artifactory.pegadaian.co.id:8084/docker:dind
      command: ["--insecure-registry=artifactory.pegadaian.co.id:8084"]
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:8084
    - docker build --pull -t $IMAGE_URL .
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:5443
    - docker push $IMAGE_URL
