version: '3'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 54321:5432

  app:
    build: .
    ports:
      - 9090:9090
    environment:
      - PORT=9090
      - CONTEXT_TIMEOUT=2
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PORT=
      - DB_PASS=
      - DB_NAME=goldcarddb
      - DB_LOGGER=false
      - WITH_JWT=true
      - JWT_SECRET=samandajimmy
      - JWT_TOKEN_EXP=24
      - BASIC_USERNAME=jsr
      - BASIC_PASSWORD=jsr
      - BRI_HOST=https://sandbox.partner.api.bri.co.id
      - BRI_GRANT_TYPE=client_credentials
      - BRI_CLIENT_ID=YtkJkC2vrGGxsD7KVjSLWAk38cPq4thm
      - BRI_CLIENT_SECRET=HG2X0VaAP0nRmc4X
      - PDS_API_BASIC_USER=aplikasijs
      - PDS_API_BASIC_PASS=aplikasi123
      - PDS_API_HOST=https://apidigitaldev.pegadaian.co.id/v4
      - CONFIG_DIR=/src/gade/srv-goldcard/configs
      - SWITCHING_HOST=https://devpds.pegadaian.co.id:9080
      - SWITCHING_CLIENT_ID=9997
      - SWITCHING_CHANNEL_ID=6017
      - SWITCHING_USERNAME=aplikasijs
      - SWITCHING_PASSWORD=aplikasi123
      - SWITCHING_PASSWORD_TOKEN=pgd123!
      - SWITCHING_FLAG=K
      - RETRY_ON_ERR=3

