version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - CONTEXT_TIMEOUT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_PORT=
      - DB_NAME=
      - DB_SSLMODE=
      - PORT=
      - JWT_SECRET=
      - JWT_TOKEN_EXP=
      - BASIC_USERNAME=
      - BASIC_PASSWORD=
      - CONFIG_DIR=
      - BRI_HOST=
      - BRI_GRANT_TYPE=
      - BRI_CLIENT_ID=
      - BRI_CLIENT_SECRET=
      - PDS_API_BASIC_USER=
      - PDS_API_BASIC_PASS=
      - PDS_API_HOST=
      - SWITCHING_HOST=
      - SWITCHING_CLIENT_ID=
      - SWITCHING_CHANNEL_ID=
      - SWITCHING_USERNAME=
      - SWITCHING_PASSWORD=
      - SWITCHING_PASSWORD_TOKEN=