version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - CONTEXT_TIMEOUT=2000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=
      - DB_PORT=
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - PORT=8080
      - JWT_SECRET=docker-compose-secret
      - JWT_TOKEN_EXP=24
      - BASIC_USERNAME=docker-admin
      - BASIC_PASSWORD=docker-admin123
      - UPLOAD_IMAGE_URL=http://pds-api.hookiarisan.com/gpoint/voucherimage/add