version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT="9090"
      - CONTEXT_TIMEOUT=
      - DB_HOST="db"
      - DB_PORT=
      - DB_USER="postgres"
      - DB_PASS=
      - DB_NAME="postgres"
      - JWT_SECRET="secret"
      - JWT_TOKEN_EXP="3600"
      - BASIC_USERNAME="basic_user"
      - BASIC_PASSWORD="basic_pass"
      - BRI_HOST="https://sandbox.partner.api.bri.co.id"
      - BRI_GRANT_TYPE="client_credentials"
      - BRI_CLIENT_ID="YtkJkC2vrGGxsD7KVjSLWAk38cPq4thm"
      - BRI_CLIENT_SECRET="HG2X0VaAP0nRmc4X"
      - PDS_API_BASIC_USER="aplikasijs"
      - PDS_API_BASIC_PASS="aplikasi123"
      - PDS_API_HOST="https://apidigitaldev.pegadaian.co.id/v2"
      - CONFIG_DIR="/src/gade/srv-goldcard/configs"
      - SWITCHING_HOST="https://devpds.pegadaian.co.id:7088"
      - SWITCHING_CLIENT_ID="9997"
      - SWITCHING_CHANNEL_ID="6017"
      - SWITCHING_USERNAME="aplikasijs"
      - SWITCHING_PASSWORD="aplikasi123"
      - SWITCHING_PASSWORD_TOKEN="pgd123!"