version: '3'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 54321:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    ports:
      - 8084:8084
    env_file:
      - .env