version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - CONTEXT_TIMEOUT=2000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=
      - DB_PORT=
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - PORT=8080
      - JWT_SECRET=gade-secret
      - JWT_TOKEN_EXP=720
      - BASIC_USERNAME=admin
      - BASIC_PASSWORD=admin
      - UPLOAD_IMAGE_URL=http://pds-api.hookiarisan.com/gpoint/voucherimage/add
      - STATUS_UPDATE_TIME=
      - UPLOAD_IMAGE_URL=
      - REWARD_TRX_TIMEOUT=
      - PDS_API_HOST=aplikasijs
      - SEND_SMS_PROMO=aplikasi123
      - PDS_API_HOST=https://apidigitaldev123.pegadaian.co.id/v2
      - SEND_SMS_PROMO_PATH=/notification/send_sms_promo
      - CS_NUMBER_1=085959114119
      - CS_NUMBER_2=089603239653
      - CONFIG_DIR=/configs
      - BRI_HOST=https://sandbox.partner.api.bri.co.id
      - BRI_GRANT_TYPE=client_credentials
      - BRI_CLIENT_ID=YtkJkC2vrGGxsD7KVjSLWAk38cPq4thm
      - BRI_CLIENT_SECRET=HG2X0VaAP0nRmc4X
      - PDS_API_BASIC_USER=aplikasijs
      - PDS_API_BASIC_PASS=aplikasi123
      - PDS_API_HOST=https://apidigitaldev.pegadaian.co.id/v2
      - SWITCHING_HOST=https://devpds.pegadaian.co.id:7088
      - SWITCHING_CLIENT_ID=9997
      - SWITCHING_CHANNEL_ID=6017
      - SWITCHING_USERNAME=aplikasijs
      - SWITCHING_PASSWORD=aplikasi123
      - SWITCHING_PASSWORD_TOKEN=pgd123!