version: '3'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 54321:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - db
    environment:
      - PORT=9090
      - CONTEXT_TIMEOUT=2
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PORT=
      - DB_PASS=
      - DB_NAME=postgres
      - DB_LOGGER=false
      - WITH_JWT=true
      - JWT_SECRET=samandajimmy
      - JWT_TOKEN_EXP=24
      - BASIC_USERNAME=jsr
      - BASIC_PASSWORD=jsr
      - BRI_HOST=
      - BRI_GRANT_TYPE=
      - BRI_CLIENT_ID=
      - BRI_CLIENT_SECRET=
      - BRI_BASE_PATH=
      - PDS_API_BASIC_USER=
      - PDS_API_BASIC_PASS=
      - PDS_API_HOST=
      - SWITCHING_HOST=
      - SWITCHING_CLIENT_ID=
      - SWITCHING_CHANNEL_ID=
      - SWITCHING_USERNAME=
      - SWITCHING_PASSWORD=
      - SWITCHING_PASSWORD_TOKEN=
      - SWITCHING_FLAG=
      - RETRY_ON_ERR=3
      - WITH_REGISTRATION=false