requirements:
    aktivasiFinansial: true
    registrasiGTE: true
    saldoTabunganEmas: true
    openTE: true
    umur: 21
    kyc: true
    saldoMinEfektif: 0.1
    limitPengajuan: 
        max: 999000000
        min: 3000000